RootConfig:
    #   ---
    #   Config allows for multiple CloudFormation Scripts to be generated at a scalable level
    #   Specify Service Type along with Parameters, Service Types can be duplicated to create multiples
    #   of the same service with matching or different parameters. Note each Service Type will need the
    #   SPECIFIC service name along with additional names suited to your needs. This will result in the
    #   stack-name of your service Cloud Formation Script.
    #   ---
    #   If Parameter is not required, leave its value BLANK and PyCloudFormer will not add it to the
    #   final output file. If an entire service is not required, remove the Stack entirely and PyCloudFormer
    #   will not add it to the final output file.
    #   ---

    GlueJob:
        AllocatedCapacity: None
        CommandName: String
        CommandPythonVersion: String
        CommandScriptLocation: String
        Connections:
            - String
        DefaultArguments: Json
        Description: String
        MaxConcurrentRuns: Double
        GlueVersion: String
        LogUri: String
        MaxCapacity: Double
        MaxRetries: Double
        Name: String
        NumberOfWorkers: Integer
        Role: String
        SecurityConfiguration: String
        WorkerType: String

    GlueClassifier:
        Name: String
        Classification: String
        CsvClassifier:
            AllowSingleColumn: Boolean
            ContainsHeader: String
            Delimiter: String
            DisableValueTrimming: Boolean
            Header:
                - String
            QuoteSymbol: String
        GrokClassifier:
            CustomPatterns: String
            GrokPattern: String
        JsonClassifier:
            JsonPath: String
        XMLClassifier:
            RowTag: String

    GlueDatabase:
        CatalogId: String
        Description: String
        LocationUri: String
        Name: String
        Parameters: Json

    GlueCrawler:
        Classifiers:
            - String
        Configuration: String
        CrawlerSecurityConfiguration: String
        DatabaseName: String
        Description: String
        Name: String
        Role: String
        ScheduleExpression: String
        DeleteBehavior: String
        UpdateBehavior: String
        TablePrefix: String
        Tags: Json
        JdbcTargets:
            - JdbcTarget
        S3Targets:
            - String

    S3Bucket:
        Description: String
        AccelerationStatus: String
        KMSMasterKeyID: String
        SSEAlgorithm: String
        BucketName: String
        VersioningConfiguration: String
        BlockPublicAcls: Boolean
        BlockPublicPolicy: Boolean
        IgnorePublicAcls: Boolean
        RestrictPublicBuckets: Boolean

